version: '3'
services:
  vita-fe:
    container_name: vita-fe
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '80'
    environment:
          VIRTUAL_HOST: vita.node404.com
          LETSENCRYPT_HOST: vita.node404.com
          LETSENCRYPT_EMAIL: kmplavelle@gmail.com
    networks:
      - webproxy
      - reverse-proxy-network

networks:    
    webproxy:
        external: true
    reverse-proxy-network:
        external: true