version: '3'
services:
  vita-fe:
    container_name: vita-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7995:80'
    expose:
      - '80'
    environment:
          VIRTUAL_PORT: 7995
          VIRTUAL_HOST: vita.node404.com
          LETSENCRYPT_HSOT: vita.node404.com
          LETSENCRYPT_EMAIL: kmplavelle@gmail.com
    networks:
      - webproxy

networks:    
    webproxy:
        external: true