version: "3"
services:
    vita-fe:
        container_name: vita-fe
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - reverse-proxy-network

networks:
    reverse-proxy-network:
        external: true