version: '3'
services:
  identity-fe:
    container_name: vita-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7995:80'
    networks:
      - reverse-proxy-network

networks:
  reverse-proxy-network:
    external:
      name: reverse-proxy-network